### PR TITLE
Append a semicolon to a SQL

### LINKED ISSUE #25: Handle missing semicolon
If a user forgot ";" at the end of a SQL statement. The current implementation will return `parseResponseBody error: 400`, which is not informative.

We should either
1. Print more informative error messages
1. Autocomplete the ";"

Code to reproduce:

```go
package main

import (
	"fmt"
	"os"
	"sqlflow.org/gomaxcompute"
	"database/sql"
)

func main() {
	config := gomaxcompute.Config{...}

	db, _ := sql.Open("maxcompute", config.FormatDSN())
	assertNoErr(err)

	// Will raise "parseResponseBody error: 400"
	rows, err := db.Query("SELECT * FROM yiyang_test_table1") // forgot to add ";" in the end
	fmt.Println(err)
}
```

### PR DESCRIPTION
**Pull request by weiguoz**
fix #25

### CODE REVIEW

File: connection_test.go [hunk 1]
```diff
@@ -12,7 +12,7 @@ func TestQuery(t *testing.T) {
 	db, err := sql.Open("maxcompute", cfg4test.FormatDSN())
 	a.NoError(err)
 
-	const stmt = `SELECT * FROM gomaxcompute_test LIMIT 1;`
+	const stmt = `SELECT * FROM gomaxcompute_test LIMIT 1`
```
Comment (tonyyang-svail) [inline connection_test.go]: How about testing this separately? So that we can make sure the original test doesn't break.

**Review by tonyyang-svail — APPROVED** [review]

File: connection_test.go (hunk 1 above)
Comment (weiguoz) [reply connection_test.go]: You're right!
