### PR TITLE
Better error message

### LINKED ISSUE #43: Add XML parsing for errors
On invalid SQL syntax, the server returns 400 with the following error messages. We should support parsing them.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
	<Code>ParseError</Code>
	<Message><![CDATA[ODPS-0130161:[1,1] Parse exception - invalid token 'SLEECT']]></Message>
	<RequestId>5583C0893F7EC2D353</RequestId>
	<HostId>odps.aliyun.com</HostId>
</Error>
```

### PR DESCRIPTION
**Pull request by tonyyang-svail**
Fix #43.

To get the error code in another package, try
```go
_, err := db.Query(...)
me, ok := err.(maxcompute.MaxcomputeError)
if !ok {
    ....
}

// 0130131 means table not found
// ref: https://www.alibabacloud.com/help/doc-detail/64654.htm
if me.Code == `0130131` {
    // do stuff
}
```

### CODE REVIEW

File: instance.go [hunk 1]
```diff
@@ -25,6 +25,18 @@ type instanceResult struct {
 	Result  Result   `xml:"Tasks>Task>Result"`
 }
 
+type instanceErrorMessage struct {
+	CDATA string `xml:",cdata"`
+}
+
+type instanceError struct {
```
Comment (weiguoz) [inline instance.go:32]: Is it the general error of instance, or only for the status code 400?

Comment (tonyyang-svail) [reply instance.go:32]: You are right. Probably should name it to `requestError`?

Comment (weiguoz) [reply instance.go:32]: `requestError` is better.
But I'm worried about if there're still several error message structs not involved.
How about we take a look at [aliyun-odps-jdbc](https://github.com/aliyun/aliyun-odps-jdbc) or [aliyun-odps-python-sdk](https://github.com/aliyun/aliyun-odps-python-sdk)?

Comment (tonyyang-svail) [reply instance.go:32]: Looks like there is only one error struct. :) https://github.com/aliyun/aliyun-odps-java-sdk/blob/master/odps-sdk/odps-sdk-core/src/main/java/com/aliyun/odps/rest/ErrorMessage.java

**Review by weiguoz — APPROVED** [review]
LGTM
